# Generated by Django 5.2.12 on 2026-04-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locator', models.CharField(max_length=50, unique=True)),
                ('lead_name', models.CharField(max_length=150)),
                ('excursion_id', models.IntegerField()),
                ('hotel_id', models.IntegerField()),
                ('service_date', models.DateField()),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('infants', models.PositiveIntegerField(default=0)),
                ('language', models.CharField(default='en', max_length=10)),
                ('agency', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
