# Generated by Django 5.2.12 on 2026-04-26 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_agency_excursion_hotel_provider_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservations.agency'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='excursion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.excursion'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='reservations.hotel'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='lead_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='locator',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
