# Generated by Django 5.2.12 on 2026-05-05 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_excursion_description_alter_excursion_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, max_length=180)),
                ('vehicle_name', models.CharField(blank=True, max_length=120)),
                ('driver_name', models.CharField(blank=True, max_length=120)),
                ('driver_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to provider'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='reservations.excursion')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='reservations.provider')),
                ('reservations', models.ManyToManyField(blank=True, related_name='operations', to='reservations.reservation')),
            ],
            options={
                'ordering': ['-date', 'excursion__name', 'provider__name'],
            },
        ),
    ]
