# Generated by Django 5.2.12 on 2026-05-05 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='provider_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='reservations.providerservice'),
        ),
    ]
