# Generated by Django 5.2.12 on 2026-05-06 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_operation_provider_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='excursion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='reservations.excursion'),
        ),
    ]
