# Generated by Django 5.2.12 on 2026-05-10 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_operation_excursion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyExcursionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('child_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('DOP', 'DOP'), ('EUR', 'EUR')], default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursion_prices', to='reservations.agency')),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_prices', to='reservations.excursion')),
            ],
            options={
                'ordering': ['agency__name', 'excursion__name'],
                'unique_together': {('agency', 'excursion')},
            },
        ),
    ]
