# Generated by Django 5.2.12 on 2026-05-10 18:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_agencyexcursionprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationcost',
            name='agency_commission',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='reservationcost',
            name='agency_owes_us',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reservationcost',
            name='card_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reservationcost',
            name='card_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('12.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='reservationcost',
            name='collection_type',
            field=models.CharField(choices=[('we_collect_full', 'We collect full amount'), ('agency_collects_full', 'Agency collects full amount'), ('agency_collects_commission', 'Agency collects commission only'), ('agency_pays_balance', 'Agency pays balance')], default='we_collect_full', max_length=40),
        ),
        migrations.AddField(
            model_name='reservationcost',
            name='customer_paid_to_agency',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='reservationcost',
            name='customer_paid_to_us',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='reservationcost',
            name='final_total_with_card_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='reservationcost',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('bank_transfer', 'Bank transfer'), ('agency_collects', 'Agency collects'), ('mixed', 'Mixed')], default='cash', max_length=30),
        ),
        migrations.AddField(
            model_name='reservationcost',
            name='we_owe_agency',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
