# Generated by Django 6.0.3 on 2026-03-21 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('participants', models.PositiveIntegerField(default=0)),
                ('client_name', models.CharField(max_length=255)),
                ('room_no', models.CharField(blank=True, max_length=100)),
                ('punctuality', models.PositiveSmallIntegerField(default=0)),
                ('transport', models.PositiveSmallIntegerField(default=0)),
                ('guide_rating', models.PositiveSmallIntegerField(default=0)),
                ('food', models.PositiveSmallIntegerField(default=0)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excursion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.excursion')),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.guide')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.hotel')),
                ('tour_operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='surveys.touroperator')),
            ],
        ),
    ]
